-- Notification preferences: quiet hours and per-channel toggles
ALTER TABLE users ADD COLUMN IF NOT EXISTS quiet_hours_start TIME DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS quiet_hours_end TIME DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_push BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_email BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_sms BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_weekly_digest BOOLEAN DEFAULT TRUE;
